Vagrant.configure(2) do |config| #2 corresponds to configuration version
  config.vm.box = "jsonc/centos7" # name of the vbox
  config.vm.hostname = "testbox01"
  config.vm.network "private_network", ip:"192.168.56.2"
end
